baseURL = "http://www.swpatterns.com/"
languageCode = "en-us"
title = "SWPatterns.com"
theme = "hugo-clarity-new"

showShare = true


[taxonomies]
pattern_types = "pattern_types"
language = "language"
pattern_usage = "pattern_usage"

[params]
mainSections = ["pattern", "language"]

[menu]

  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-house'></i>"
    url = "/"
    weight = -110

  [[menu.main]]
    name = "Patterns"
    url = "/pattern/"
    weight = -100

  [[menu.main]]
    name = "Languages"
    url = "/language/"
    weight = -70

  [[menu.main]]
    name = "Contribute"
    pre = "<i class='fa fa-gh'></i>"
    url = "https://github.com/swpatterns/swpatterns.com"
    weight = -50
